### ISSUE TITLE
As a user, I want to see what a user has posted before

### ISSUE THREAD

**Issue by Zain-MKhan** [SOEN341Project/instantgram.github.io#141]
Description:
I want to see other users' older posts

Steps:
-Establish user profiles, be able to navigate to these profiles
-Display profile page with photo gallery of these users, identical to logged in user's profile page

Priority: High

Story Points: 2

Risk: Low

**Comment by BozhidarLeshev** [comment]
It was a

**Comment by BozhidarLeshev** [comment]
It is done
